---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8080, host: 8081}]

provisioner:
  name: policyfile_zero
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    attributes:
